services:
  - type: web
    name: property-maintenance-lite
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: property-maintenance-db
          property: connectionString

databases:
  - name: property-maintenance-db
    plan: free