name: Run Migrations on Render
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install -r requirements.txt
          python manage.py migrate --noinput
        env:
          DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}
          SECRET_KEY: test
          DEBUG: "False"
